# Configuração do Cluster: 1 node master e 2 nodes worker


kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
        - role: control-plane
        - role: worker1
        - role: worker2  
          
