apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
        name: processor
        namespace: virtualizacao
subjects:
        - kind: User
          name: processor
          apiGroup: rbac.authorization.k8s.io
roleRef:
        kind: Role
        name: processor
        apiGroup: rbac.autorization.k8s.io
