apiVersion: v1
kind: Deployment
metadata:
        name: deployment
spec:
        selector:
                replicas: 3
                matchLabels:
                        key: vol
        containers:
                        - name: container1           
                          image: httpd:2.4.41-alpine
        volumes:
                - name: virt-pv
                  hostPath:
                          path: /tmp/data
