apiVersion: v1
kind: PersistentVolumeClaim
metada:
        name: virt-pvc
spec:
        accessModes:
                - ReadWriteOnce
        resources:
                requests:
                        storage: 2Gi
        selector:
                mathcLabels:
                        component: redis
