apiVersion: v1
kind: PersistentVolume
metadata:
        name: virt-pv
        labels:
                component: redis
spec:
        volumes:
                - name: virt-pv
                  hostPath:
                          path: /Volumes/data
        capacity:
                storage: 2Gi
        accessModes:
                - ReadWriteOnce

