apiVersion: v1
kind: Pod
metadata:
        name: pod
        labels:
                environment: muito-importante
                app: nginx
spec:
        containers:
                - name: container1
                  image: nginx:1.17.6-alpine
                - name: container2
                  image: kubernetes/pause
        tolerations:
                - key: "key1"
                  operator: "Equal"
                  value: "value1"
                  effect: "NoSchedule"
